name: Build uke USER_NS kernel

on:
  push:
    branches:
      - uke-userns
    paths:
      - .github/workflows/uke-userns-build.yml
      - .github/workflows/prepare.yml
      - .github/workflows/build.yml
      - .github/config/android14-6.1.json
      - .github/actions/droidspaces/**
      - .github/actions/ntsync/**
      - .github/actions/build-kernel/**
      - .github/actions/kernelsu/**

permissions:
  contents: write
  actions: write

jobs:
  build:
    uses: ./.github/workflows/prepare.yml
    with:
      config_file: .github/config/android14-6.1.json
      feature_set: KSUN+DS
      ksu_branch: ""
      susfs_commit: ""
    secrets: inherit
